import type { IncomingMessage, ServerResponse } from "node:http";
import { git, gitStatus } from "../../orchestrator/git-service.ts";

export type Ctx = { safePath(input: string): string; ok(response: ServerResponse, data: unknown, status?: number): void; error(response: ServerResponse, status: number, message: string): void; body<T>(request: IncomingMessage): Promise<T> };

export const gitRoutes = {
  async status(ctx: Ctx, url: URL, response: ServerResponse) { ctx.ok(response, await gitStatus(ctx.safePath(url.searchParams.get("cwd") ?? ""))); },
  async branches(ctx: Ctx, url: URL, response: ServerResponse) { const output = await git(ctx.safePath(url.searchParams.get("cwd") ?? ""), ["branch", "--format=%(refname:short)\t%(HEAD)\t%(upstream:short)"]); ctx.ok(response, output.split("\n").filter(Boolean).map((line) => { const [name, head, upstream] = line.split("\t"); return { name, current: head === "*", upstream: upstream || null }; })); },
  async diff(ctx: Ctx, url: URL, response: ServerResponse) { ctx.ok(response, { diff: await git(ctx.safePath(url.searchParams.get("cwd") ?? ""), ["diff", "--no-ext-diff"]), files: [] }); },
  async diffFile(ctx: Ctx, url: URL, response: ServerResponse) {
    const cwd = ctx.safePath(url.searchParams.get("cwd") ?? "");
    const path = url.searchParams.get("path") ?? "";
    const staged = url.searchParams.get("staged") === "true";
    const diff = await git(cwd, ["diff", "--no-ext-diff", ...(staged ? ["--cached"] : []), "--", path]);
    ctx.ok(response, { path, diff });
  },
  async stashList(ctx: Ctx, url: URL, response: ServerResponse) { const output = await git(ctx.safePath(url.searchParams.get("cwd") ?? ""), ["stash", "list", "--format=%gd%x00%s"]); ctx.ok(response, output.split("\n").filter(Boolean).map((line) => { const [index, message] = line.split("\0"); return { index, message }; })); },
  async stashPush(ctx: Ctx, request: IncomingMessage, response: ServerResponse, queryCwd: string | null) { const body = await ctx.body<{ cwd?: string; message?: string }>(request); const cwd = ctx.safePath(queryCwd ?? body.cwd ?? ""); ctx.ok(response, { output: await git(cwd, ["stash", "push", ...(body.message ? ["-m", body.message] : [])]), success: true }); },
  async stashApply(ctx: Ctx, request: IncomingMessage, response: ServerResponse, queryCwd: string | null) { const body = await ctx.body<{ cwd?: string; index?: number; pop?: boolean }>(request); const cwd = ctx.safePath(queryCwd ?? body.cwd ?? ""); const args = body.pop ? ["stash", "pop"] : ["stash", "apply"]; if (body.index !== undefined) args.push(`stash@{${body.index}}`); ctx.ok(response, { output: await git(cwd, args), success: true }); },
  async stashDrop(ctx: Ctx, request: IncomingMessage, response: ServerResponse, queryCwd: string | null) { const body = await ctx.body<{ cwd?: string; index?: number }>(request); const cwd = ctx.safePath(queryCwd ?? body.cwd ?? ""); ctx.ok(response, { output: await git(cwd, ["stash", "drop", ...(body.index === undefined ? [] : [`stash@{${body.index}}`])]), success: true }); },
  async worktreeList(ctx: Ctx, url: URL, response: ServerResponse) { const output = await git(ctx.safePath(url.searchParams.get("cwd") ?? ""), ["worktree", "list", "--porcelain"]); const blocks = output.split("\n\n").filter(Boolean); ctx.ok(response, blocks.map((block) => { const lines = block.split("\n"); return { path: lines.find((line) => line.startsWith("worktree "))?.slice(9) ?? "", head: lines.find((line) => line.startsWith("HEAD "))?.slice(5) ?? "", branch: lines.find((line) => line.startsWith("branch "))?.slice(7) ?? null }; })); },
  async worktreeAdd(ctx: Ctx, request: IncomingMessage, response: ServerResponse, queryCwd: string | null) { const body = await ctx.body<{ cwd?: string; path?: string; branch?: string; new_branch?: string }>(request); if (!body.path) return ctx.error(response, 422, "path is required"); const cwd = ctx.safePath(queryCwd ?? body.cwd ?? ""); const args = ["worktree", "add"]; if (body.new_branch) args.push("-b", body.new_branch); args.push(body.path, ...(body.branch ? [body.branch] : [])); ctx.ok(response, { output: await git(cwd, args), success: true }); },
  async worktreeRemove(ctx: Ctx, request: IncomingMessage, response: ServerResponse, queryCwd: string | null) { const body = await ctx.body<{ cwd?: string; path?: string }>(request); if (!body.path) return ctx.error(response, 422, "path is required"); const cwd = ctx.safePath(queryCwd ?? body.cwd ?? ""); ctx.ok(response, { output: await git(cwd, ["worktree", "remove", body.path]), success: true }); },
  async log(ctx: Ctx, url: URL, response: ServerResponse) { const cwd = ctx.safePath(url.searchParams.get("cwd") ?? ""); const output = await git(cwd, ["log", "--format=%H%x00%h%x00%an%x00%aI%x00%s", "-n", String(Math.min(100, Math.max(1, Number(url.searchParams.get("limit") ?? 30))))]); ctx.ok(response, output.split("\n").filter(Boolean).map((line) => { const [hash, short_hash, author, date, message] = line.split("\0"); return { hash, short_hash, author, date, message }; })); },
  async mutation(ctx: Ctx, request: IncomingMessage, response: ServerResponse, operation: string, queryCwd: string | null) { const body = await ctx.body<{ cwd?: string; paths?: string[] }>(request); const cwd = ctx.safePath(queryCwd ?? body.cwd ?? ""); const args = operation === "add" ? ["add", ...(body.paths ?? ["."])] : operation === "restore" ? ["restore", ...(body.paths ?? ["."])] : [operation]; ctx.ok(response, { operation, output: await git(cwd, args), success: true }); },
  async commit(ctx: Ctx, request: IncomingMessage, response: ServerResponse, queryCwd: string | null) { const body = await ctx.body<{ cwd?: string; message?: string }>(request); const output = await git(ctx.safePath(queryCwd ?? body.cwd ?? ""), ["commit", "-m", String(body.message ?? "")]); ctx.ok(response, { operation: "commit", success: true, output }); },
};
