import type { IncomingMessage, ServerResponse } from "node:http";
import { gitRoutes, type Ctx } from "./git.ts";

// The HTTP server supplies bound handlers; this module owns only method/path dispatch.
export type RouteContext = Ctx & Record<string, any>;

export async function dispatchRoute(ctx: RouteContext, request: IncomingMessage, response: ServerResponse, url: URL): Promise<void> {
  if (request.method === "GET" && ["/health", "/healthz", "/api/health"].includes(url.pathname)) return ctx.json(response, 200, { status: "ok" });
  if (request.method === "GET" && !url.pathname.startsWith("/api/") && url.pathname !== "/health" && url.pathname !== "/healthz") return ctx.web(request, response, url);
  if (request.method === "GET" && ["/version", "/api/version"].includes(url.pathname)) return ctx.version(response);
  if (request.method === "GET" && url.pathname === "/api/version/latest") return ctx.latestVersion(response);
  if (request.method === "POST" && url.pathname === "/api/devices") return ctx.createDevice(request, response);
  if (request.method === "GET" && url.pathname === "/api/devices") return ctx.listDevices(request, response);
  if (request.method === "GET" && url.pathname === "/api/devices/code") return ctx.getDeviceCode(request, response);
  if (request.method === "POST" && url.pathname === "/api/devices/code") return ctx.createDeviceCode(request, response);
  const deviceMatch = /^\/api\/devices\/([^/]+)$/.exec(url.pathname);
  if (request.method === "DELETE" && deviceMatch) return ctx.deleteDevice(request, response, deviceMatch[1]);
  if (request.method === "POST" && url.pathname === "/api/auth/logout") return ctx.logout(request, response);
  if (url.pathname === "/api/auth/session") return ctx.authorized(request) ? ctx.ok(response, null) : ctx.error(response, 401, "Unauthorized");
  if (!ctx.authenticated().initialized() && !ctx.localMode) return ctx.error(response, 503, "AiJee setup is required");
  if (!ctx.authorized(request)) return ctx.error(response, 401, "Unauthorized");
  if (request.method === "GET" && url.pathname === "/api/agent/runtime-status") return ctx.ok(response, ctx.runtimeStatus());
  if (request.method === "GET" && url.pathname === "/api/providers") return ctx.ok(response, await ctx.listBuiltinProviders());
  const providerKey = /^\/api\/providers\/([^/]+)\/api-key$/.exec(url.pathname);
  if (providerKey && request.method === "PUT") { const body = await ctx.body(request) as { api_key?: unknown }; await ctx.saveBuiltinProviderKey(providerKey[1], String(body.api_key ?? "")); return ctx.ok(response, null); }
  if (providerKey && request.method === "DELETE") { await ctx.removeBuiltinProviderKey(providerKey[1]); return ctx.ok(response, null); }
  const providerOAuth = /^\/api\/providers\/([^/]+)\/oauth(?:\/([^/]+))?$/.exec(url.pathname);
  if (providerOAuth && request.method === "POST" && !providerOAuth[2]) return ctx.ok(response, await ctx.startProviderOAuth(providerOAuth[1]));
  if (providerOAuth && request.method === "GET" && providerOAuth[2]) return ctx.ok(response, ctx.oauthStatus(providerOAuth[2]));
  const oauthPrompt = /^\/api\/providers\/[^/]+\/oauth\/([^/]+)\/prompt\/([^/]+)$/.exec(url.pathname);
  if (oauthPrompt && request.method === "POST") { const body = await ctx.body(request) as { value?: unknown }; ctx.resolveOAuthPrompt(oauthPrompt[1], oauthPrompt[2], String(body.value ?? "")); return ctx.ok(response, null); }
  if (request.method === "GET" && url.pathname === "/api/custom-models") return ctx.ok(response, await ctx.getCustomModels());
  if (request.method === "PUT" && url.pathname === "/api/custom-models") return ctx.ok(response, await ctx.saveCustomModels(await ctx.body(request)));
  if (request.method === "GET" && url.pathname === "/api/modes") return ctx.ok(response, [...ctx.modes.values()].sort((a: any, b: any) => (a.sort_order ?? 0) - (b.sort_order ?? 0)));
  if (request.method === "POST" && url.pathname === "/api/modes") return ctx.createMode(request, response);
  const modeMatch = /^\/api\/modes\/([^/]+)$/.exec(url.pathname);
  if (modeMatch) return ctx.modeRoute(request, response, modeMatch[1]);
  const sessionModeMatch = /^\/api\/sessions\/([^/]+)\/mode$/.exec(url.pathname);
  if (sessionModeMatch) return ctx.sessionMode(request, response, sessionModeMatch[1]);
  if (request.method === "GET" && url.pathname === "/api/fs/list") return ctx.fsList(url, response);
  if (request.method === "GET" && url.pathname === "/api/fs/complete") return ctx.fsComplete(url, response);
  if (request.method === "GET" && url.pathname === "/api/fs/read") return ctx.fsRead(url, response);
  if (request.method === "GET" && url.pathname === "/api/fs/download") return ctx.fsDownload(url, response);
  if (request.method === "POST" && url.pathname === "/api/fs/write") return ctx.fsWrite(request, response);
  if (request.method === "POST" && url.pathname === "/api/fs/mkdir") return ctx.fsMkdir(request, response);
  if (request.method === "DELETE" && url.pathname === "/api/fs/delete") return ctx.fsDelete(request, response);
  if (request.method === "POST" && url.pathname === "/api/fs/upload") return ctx.fsUpload(request, response, url);
  if (request.method === "GET" && url.pathname === "/api/git/status") return gitRoutes.status(ctx, url, response);
  if (request.method === "GET" && url.pathname === "/api/git/branches") return gitRoutes.branches(ctx, url, response);
  if (request.method === "GET" && url.pathname === "/api/git/diff") return gitRoutes.diff(ctx, url, response);
  if (request.method === "GET" && url.pathname === "/api/git/log") return gitRoutes.log(ctx, url, response);
  if (request.method === "GET" && url.pathname === "/api/git/repos") return ctx.error(response, 501, "Nested repository discovery is not implemented");
  if (request.method === "GET" && url.pathname === "/api/git/diff/file") return gitRoutes.diffFile(ctx, url, response);
  if (request.method === "GET" && url.pathname === "/api/git/stash") return gitRoutes.stashList(ctx, url, response);
  if (request.method === "POST" && url.pathname === "/api/git/stash") return gitRoutes.stashPush(ctx, request, response, url.searchParams.get("cwd"));
  if (request.method === "POST" && url.pathname === "/api/git/stash/apply") return gitRoutes.stashApply(ctx, request, response, url.searchParams.get("cwd"));
  if (request.method === "DELETE" && url.pathname === "/api/git/stash") return gitRoutes.stashDrop(ctx, request, response, url.searchParams.get("cwd"));
  if (request.method === "GET" && url.pathname === "/api/git/worktrees") return gitRoutes.worktreeList(ctx, url, response);
  if (request.method === "POST" && url.pathname === "/api/git/worktrees") return gitRoutes.worktreeAdd(ctx, request, response, url.searchParams.get("cwd"));
  if (request.method === "DELETE" && url.pathname === "/api/git/worktrees") return gitRoutes.worktreeRemove(ctx, request, response, url.searchParams.get("cwd"));
  if (request.method === "POST" && url.pathname === "/api/git/checkout") return gitRoutes.mutation(ctx, request, response, "checkout", url.searchParams.get("cwd"));
  if (request.method === "POST" && url.pathname === "/api/git/stage") return gitRoutes.mutation(ctx, request, response, "add", url.searchParams.get("cwd"));
  if (request.method === "POST" && url.pathname === "/api/git/unstage") return gitRoutes.mutation(ctx, request, response, "reset", url.searchParams.get("cwd"));
  if (request.method === "POST" && url.pathname === "/api/git/discard") return gitRoutes.mutation(ctx, request, response, "restore", url.searchParams.get("cwd"));
  if (request.method === "POST" && url.pathname === "/api/git/commit") return gitRoutes.commit(ctx, request, response, url.searchParams.get("cwd"));
  if (request.method === "GET" && url.pathname === "/api/package/status") return ctx.ok(response, await ctx.packageStatus());
  if (request.method === "GET" && url.pathname === "/api/package/logs") return ctx.ok(response, await ctx.packageLogs(Number(url.searchParams.get("limit") ?? 50)));
  if (request.method === "POST" && url.pathname === "/api/package/install") return ctx.ok(response, await ctx.packageInstall());
  if (request.method === "POST" && url.pathname === "/api/package/update") return ctx.ok(response, await ctx.packageUpdate());
  if (request.method === "GET" && url.pathname === "/api/packages") return ctx.ok(response, await ctx.marketplaceSearch(url));
  if (request.method === "GET" && url.pathname === "/api/packages/installed") return ctx.ok(response, await ctx.marketplaceInstalled());
  if (request.method === "POST" && url.pathname === "/api/packages/operation") return ctx.ok(response, await ctx.marketplaceOperation(await ctx.body(request)));
  if (request.method === "POST" && url.pathname === "/api/packages/operation/cancel") return ctx.ok(response, ctx.marketplaceCancel());
  const packageMatch = /^\/api\/packages\/(.+)$/.exec(url.pathname);
  if (request.method === "GET" && packageMatch) return ctx.ok(response, await ctx.marketplaceDetail(decodeURIComponent(packageMatch[1]!)));
  if (["/api/desktop/backends", "/api/desktop/status", "/api/desktop/start", "/api/desktop/stop"].includes(url.pathname)) return ctx.error(response, 501, "Desktop control is owned by the Electron shell");
  if (url.pathname === "/api/preview/ws" || url.pathname === "/api/desktop/ws" || url.pathname === "/api/ws/stream" || url.pathname === "/api/ws/stream/") return ctx.error(response, 426, "Upgrade to WebSocket");
  if (request.method === "POST" && url.pathname === "/api/ports/scan") return ctx.error(response, 501, "Port scanning is not implemented");
  if (request.method === "GET" && /^\/api\/tasks\/list\/[^/]+$/.test(url.pathname)) return ctx.listTasks(url, response);
  if (request.method === "GET" && /^\/api\/tasks\/config\/[^/]+$/.test(url.pathname)) return ctx.taskConfig(url, response);
  if (request.method === "GET" && /^\/api\/tasks\/logs\/[^/]+$/.test(url.pathname)) return ctx.taskLogs(url.pathname, response);
  if (request.method === "POST" && url.pathname === "/api/tasks/start") return ctx.startTask(request, response);
  if (request.method === "POST" && url.pathname === "/api/tasks/stop") return ctx.stopTask(request, response);
  if (request.method === "POST" && url.pathname === "/api/tasks/restart") return ctx.restartTask(request, response);
  if (request.method === "DELETE" && /^\/api\/tasks\/remove\/[^/]+$/.test(url.pathname)) return ctx.removeTask(url.pathname, response);
  if (request.method === "GET" && url.pathname === "/api/workspaces") return ctx.listWorkspaces(url, response);
  if (request.method === "POST" && url.pathname === "/api/workspaces") return ctx.createWorkspace(request, response);
  if (request.method === "GET" && url.pathname === "/api/workspaces/suggest") return ctx.error(response, 501, "Workspace suggestion is not implemented");
  const workspaceSessionMatch = /^\/api\/workspaces\/([^/]+)\/sessions(?:\/([^/]+))?(?:\/(tree|leaf|archive|children|branch)(?:\/([^/]+))?)?$/.exec(url.pathname);
  if (workspaceSessionMatch) return ctx.workspaceSessionRoute(request, response, workspaceSessionMatch[1], workspaceSessionMatch[2], workspaceSessionMatch[3], workspaceSessionMatch[4]);
  const workspaceMatch = /^\/api\/workspaces\/([^/]+)(?:\/(archive|unarchive))?$/.exec(url.pathname);
  if (workspaceMatch) return ctx.workspaceRoute(request, response, workspaceMatch[1], workspaceMatch[2]);
  if (request.method === "GET" && url.pathname === "/api/agent/sessions") return ctx.ok(response, ctx.listSessions());
  if (request.method === "POST" && url.pathname === "/api/agent/sessions") return ctx.createSession(request, response);
  const previewMatch = /^\/api\/agent\/sessions\/([^/]+)\/preview\/(localhost|127\.0\.0\.1|::1)\/(\d+)(?:\/(.*))?$/.exec(url.pathname);
  if (previewMatch) return ctx.preview(request, response, previewMatch[1], previewMatch[2], previewMatch[3], previewMatch[4] ?? "");
  const agentTouchMatch = /^\/api\/agent\/sessions\/([^/]+)\/touch$/.exec(url.pathname);
  if (request.method === "POST" && agentTouchMatch) return ctx.touchAgentSession(request, response, agentTouchMatch[1]);
  if (request.method === "GET" && url.pathname === "/api/chat/sessions") return ctx.listChatSessions(url, response);
  if (request.method === "POST" && url.pathname === "/api/chat/sessions") return ctx.createChatSession(request, response);
  if (request.method === "POST" && url.pathname === "/api/agent/prompt") return ctx.prompt(request, response, "prompt");
  if (request.method === "POST" && url.pathname === "/api/agent/steer") return ctx.prompt(request, response, "steer");
  if (request.method === "POST" && url.pathname === "/api/agent/follow-up") return ctx.prompt(request, response, "followUp");
  if (request.method === "POST" && url.pathname === "/api/agent/abort") return ctx.abort(request, response);
  if (request.method === "POST" && url.pathname === "/api/agent/cycle-model") return ctx.sessionCommand(request, response, (session: any) => session.cycleModel(), "models");
  if (request.method === "POST" && url.pathname === "/api/agent/bash") return ctx.agentBash(request, response);
  if (request.method === "POST" && url.pathname === "/api/agent/export-html") return ctx.sessionCommand(request, response, async (session: any, body: any) => ({ path: await session.exportHtml(body.outputPath) }));
  if (request.method === "POST" && url.pathname === "/api/agent/fork") return ctx.sessionCommand(request, response, (session: any, body: any) => session.fork(String(body.entryId ?? body.entry_id)), "fork");
  if (request.method === "POST" && url.pathname === "/api/agent/clone") return ctx.sessionCommand(request, response, (session: any) => session.fork(String((session.entries() as Array<Record<string, any>>).at(-1)?.id ?? "")), "fork");
  if (request.method === "POST" && url.pathname === "/api/agent/fork-messages") return ctx.sessionCommand(request, response, (session: any) => ({ messages: session.forkMessages() }), "fork");
  if (request.method === "POST" && url.pathname === "/api/agent/last-assistant-text") return ctx.sessionCommand(request, response, (session: any) => ({ text: session.lastAssistantText() }));
  if (request.method === "POST" && url.pathname === "/api/agent/commands") return ctx.sessionCommand(request, response, (session: any) => ({ commands: session.commands() }), "extensions");
  if (request.method === "POST" && url.pathname === "/api/agent/extension-ui-response") return ctx.error(response, 501, "Extension UI responses are not implemented");
  if (request.method === "POST" && url.pathname === "/api/agent/state") return ctx.sessionCommand(request, response, (session: any) => session.state());
  if (request.method === "POST" && url.pathname === "/api/agent/messages") return ctx.sessionCommand(request, response, (session: any) => ({ messages: session.messages() }));
  if (request.method === "POST" && url.pathname === "/api/agent/models") return ctx.sessionCommand(request, response, (session: any) => ({ models: session.listModels() }), "models");
  if (request.method === "POST" && url.pathname === "/api/agent/set-model") return ctx.mutateSession(request, response, (session: any, body: any) => session.setModel(String(body.provider), String(body.modelId ?? body.model_id)), "models");
  if (request.method === "POST" && url.pathname === "/api/agent/thinking-levels") return ctx.sessionCommand(request, response, (session: any) => ({ levels: session.listThinkingLevels() }));
  if (request.method === "POST" && url.pathname === "/api/agent/cycle-thinking") return ctx.sessionCommand(request, response, (session: any) => session.cycleThinkingLevel());
  if (request.method === "POST" && url.pathname === "/api/agent/set-thinking") return ctx.mutateSession(request, response, (session: any, body: any) => session.setThinkingLevel(String(body.level)));
  if (request.method === "POST" && url.pathname === "/api/agent/set-steering-mode") return ctx.mutateSession(request, response, (session: any, body: any) => session.setSteeringMode(String(body.mode) as "all" | "one-at-a-time"));
  if (request.method === "POST" && url.pathname === "/api/agent/set-follow-up-mode") return ctx.mutateSession(request, response, (session: any, body: any) => session.setFollowUpMode(String(body.mode) as "all" | "one-at-a-time"));
  if (request.method === "POST" && url.pathname === "/api/agent/compact") return ctx.mutateSession(request, response, (session: any, body: any) => session.compact(body.customInstructions), "compaction");
  if (request.method === "POST" && url.pathname === "/api/agent/set-auto-compaction") return ctx.mutateSession(request, response, (session: any, body: any) => session.setAutoCompaction(Boolean(body.enabled)), "compaction");
  if (request.method === "POST" && url.pathname === "/api/agent/set-auto-retry") return ctx.mutateSession(request, response, (session: any, body: any) => session.setAutoRetry(Boolean(body.enabled)), "retry");
  if (request.method === "POST" && url.pathname === "/api/agent/abort-retry") return ctx.mutateSession(request, response, (session: any) => session.abortRetry(), "retry");
  if (request.method === "POST" && url.pathname === "/api/agent/abort-bash") return ctx.mutateSession(request, response, (session: any) => session.abortBash(), "bash");
  if (request.method === "POST" && url.pathname === "/api/agent/session-stats") return ctx.sessionCommand(request, response, (session: any) => session.sessionStats());
  if (request.method === "POST" && url.pathname === "/api/agent/entries") return ctx.sessionCommand(request, response, (session: any, body: any) => session.entries(body.since));
  if (request.method === "POST" && url.pathname === "/api/agent/tree") return ctx.sessionCommand(request, response, (session: any) => session.tree(), "sessionHistory");
  if (request.method === "POST" && url.pathname === "/api/agent/set-session-name") return ctx.mutateSession(request, response, (session: any, body: any) => session.setSessionName(String(body.name)));
  if (request.method === "POST" && url.pathname === "/api/agent/new-session") return ctx.replaceSession(request, response, "new");
  if (request.method === "POST" && url.pathname === "/api/agent/switch-session") return ctx.replaceSession(request, response, "switch");
  const historyMatch = /^\/api\/sessions\/([^/]+)\/history$/.exec(url.pathname);
  if (request.method === "GET" && historyMatch) return ctx.sessionHistory(historyMatch[1], url, response);
  const streamMatch = /^\/api\/stream\/([^/]+)$/.exec(url.pathname);
  if (request.method === "GET" && streamMatch) return ctx.stream(request, streamMatch[1], response);
  if (request.method === "GET" && url.pathname === "/api/stream") return ctx.globalStream(request, response);
  if (request.method === "POST" && url.pathname === "/api/stream-active-session") return ctx.ok(response, null);
  const chatSessionMatch = /^\/api\/chat\/sessions\/([^/]+)(?:\/touch)?$/.exec(url.pathname);
  if (chatSessionMatch && request.method === "DELETE") return ctx.deleteSession(chatSessionMatch[1], response);
  if (chatSessionMatch && request.method === "POST") return ctx.touchChatSession(request, response, chatSessionMatch[1]);
  const sessionMatch = /^\/api\/agent\/sessions\/([^/]+)$/.exec(url.pathname);
  if (request.method === "DELETE" && sessionMatch) return ctx.deleteSession(sessionMatch[1], response);
  return ctx.error(response, 404, "Route not found");
}
