/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './__root'
import { Route as AppRouteImport } from './_app'
import { Route as ConnectRouteImport } from './connect'
import { Route as AppIndexRouteImport } from './_app/index'
import { Route as AppPackagesRouteImport } from './_app/packages'
import { Route as AppServersRouteImport } from './_app/servers'
import { Route as AppSettingsIndexRouteImport } from './_app/settings/index'
import { Route as AppSettingsSectionRouteImport } from './_app/settings/$section'
import { Route as AppWorkIndexRouteImport } from './_app/work/index'
import { Route as AppWorkSessionIdRouteImport } from './_app/work/$sessionId'
import { Route as AppWorkspaceWorkspaceIdIndexRouteImport } from './_app/workspace/$workspaceId/index'
import { Route as AppWorkspaceWorkspaceIdSSessionIdRouteImport } from './_app/workspace/$workspaceId/s/$sessionId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppPackagesRoute = AppPackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => AppRoute,
} as any)
const AppServersRoute = AppServersRouteImport.update({
  id: '/servers',
  path: '/servers',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsSectionRoute = AppSettingsSectionRouteImport.update({
  id: '/settings/$section',
  path: '/settings/$section',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkIndexRoute = AppWorkIndexRouteImport.update({
  id: '/work/',
  path: '/work/',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkSessionIdRoute = AppWorkSessionIdRouteImport.update({
  id: '/work/$sessionId',
  path: '/work/$sessionId',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkspaceWorkspaceIdIndexRoute =
  AppWorkspaceWorkspaceIdIndexRouteImport.update({
    id: '/workspace/$workspaceId/',
    path: '/workspace/$workspaceId/',
    getParentRoute: () => AppRoute,
  } as any)
const AppWorkspaceWorkspaceIdSSessionIdRoute =
  AppWorkspaceWorkspaceIdSSessionIdRouteImport.update({
    id: '/workspace/$workspaceId/s/$sessionId',
    path: '/workspace/$workspaceId/s/$sessionId',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/connect': typeof ConnectRoute
  '/packages': typeof AppPackagesRoute
  '/servers': typeof AppServersRoute
  '/settings/$section': typeof AppSettingsSectionRoute
  '/work/$sessionId': typeof AppWorkSessionIdRoute
  '/settings/': typeof AppSettingsIndexRoute
  '/work/': typeof AppWorkIndexRoute
  '/workspace/$workspaceId/': typeof AppWorkspaceWorkspaceIdIndexRoute
  '/workspace/$workspaceId/s/$sessionId': typeof AppWorkspaceWorkspaceIdSSessionIdRoute
}
export interface FileRoutesByTo {
  '/connect': typeof ConnectRoute
  '/packages': typeof AppPackagesRoute
  '/servers': typeof AppServersRoute
  '/': typeof AppIndexRoute
  '/settings/$section': typeof AppSettingsSectionRoute
  '/work/$sessionId': typeof AppWorkSessionIdRoute
  '/settings': typeof AppSettingsIndexRoute
  '/work': typeof AppWorkIndexRoute
  '/workspace/$workspaceId': typeof AppWorkspaceWorkspaceIdIndexRoute
  '/workspace/$workspaceId/s/$sessionId': typeof AppWorkspaceWorkspaceIdSSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/connect': typeof ConnectRoute
  '/_app/packages': typeof AppPackagesRoute
  '/_app/servers': typeof AppServersRoute
  '/_app/': typeof AppIndexRoute
  '/_app/settings/$section': typeof AppSettingsSectionRoute
  '/_app/work/$sessionId': typeof AppWorkSessionIdRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_app/work/': typeof AppWorkIndexRoute
  '/_app/workspace/$workspaceId/': typeof AppWorkspaceWorkspaceIdIndexRoute
  '/_app/workspace/$workspaceId/s/$sessionId': typeof AppWorkspaceWorkspaceIdSSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/connect'
    | '/packages'
    | '/servers'
    | '/settings/$section'
    | '/work/$sessionId'
    | '/settings/'
    | '/work/'
    | '/workspace/$workspaceId/'
    | '/workspace/$workspaceId/s/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/connect'
    | '/packages'
    | '/servers'
    | '/'
    | '/settings/$section'
    | '/work/$sessionId'
    | '/settings'
    | '/work'
    | '/workspace/$workspaceId'
    | '/workspace/$workspaceId/s/$sessionId'
  id:
    | '__root__'
    | '/_app'
    | '/connect'
    | '/_app/packages'
    | '/_app/servers'
    | '/_app/'
    | '/_app/settings/$section'
    | '/_app/work/$sessionId'
    | '/_app/settings/'
    | '/_app/work/'
    | '/_app/workspace/$workspaceId/'
    | '/_app/workspace/$workspaceId/s/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  ConnectRoute: typeof ConnectRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/packages': {
      id: '/_app/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof AppPackagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/servers': {
      id: '/_app/servers'
      path: '/servers'
      fullPath: '/servers'
      preLoaderRoute: typeof AppServersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/$section': {
      id: '/_app/settings/$section'
      path: '/settings/$section'
      fullPath: '/settings/$section'
      preLoaderRoute: typeof AppSettingsSectionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/work/': {
      id: '/_app/work/'
      path: '/work'
      fullPath: '/work/'
      preLoaderRoute: typeof AppWorkIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/work/$sessionId': {
      id: '/_app/work/$sessionId'
      path: '/work/$sessionId'
      fullPath: '/work/$sessionId'
      preLoaderRoute: typeof AppWorkSessionIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/workspace/$workspaceId/': {
      id: '/_app/workspace/$workspaceId/'
      path: '/workspace/$workspaceId'
      fullPath: '/workspace/$workspaceId/'
      preLoaderRoute: typeof AppWorkspaceWorkspaceIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/workspace/$workspaceId/s/$sessionId': {
      id: '/_app/workspace/$workspaceId/s/$sessionId'
      path: '/workspace/$workspaceId/s/$sessionId'
      fullPath: '/workspace/$workspaceId/s/$sessionId'
      preLoaderRoute: typeof AppWorkspaceWorkspaceIdSSessionIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppPackagesRoute: typeof AppPackagesRoute
  AppServersRoute: typeof AppServersRoute
  AppIndexRoute: typeof AppIndexRoute
  AppSettingsSectionRoute: typeof AppSettingsSectionRoute
  AppWorkSessionIdRoute: typeof AppWorkSessionIdRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
  AppWorkIndexRoute: typeof AppWorkIndexRoute
  AppWorkspaceWorkspaceIdIndexRoute: typeof AppWorkspaceWorkspaceIdIndexRoute
  AppWorkspaceWorkspaceIdSSessionIdRoute: typeof AppWorkspaceWorkspaceIdSSessionIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppPackagesRoute: AppPackagesRoute,
  AppServersRoute: AppServersRoute,
  AppIndexRoute: AppIndexRoute,
  AppSettingsSectionRoute: AppSettingsSectionRoute,
  AppWorkSessionIdRoute: AppWorkSessionIdRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
  AppWorkIndexRoute: AppWorkIndexRoute,
  AppWorkspaceWorkspaceIdIndexRoute: AppWorkspaceWorkspaceIdIndexRoute,
  AppWorkspaceWorkspaceIdSSessionIdRoute:
    AppWorkspaceWorkspaceIdSSessionIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  ConnectRoute: ConnectRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
