import { Fonts } from '@/constants/theme';

export const styles = {
  overlay: { flex: 1, justifyContent: 'center', alignItems: 'center', padding: 24 },
  card: {
    width: '100%',
    maxWidth: 420,
    borderRadius: 12,
    borderWidth: 0.633,
    padding: 24,
    gap: 16,
  },
  scannerCard: { maxWidth: 440 },
  cardHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  cardTitle: { fontSize: 17, fontFamily: Fonts.sansSemiBold, textAlign: 'left' },
  cardSubtitle: { fontSize: 14, fontFamily: Fonts.sans, lineHeight: 20 },
  closeBtn: {
    width: 28,
    height: 28,
    borderRadius: 6,
    alignItems: 'center',
    justifyContent: 'center',
  },
  manualSection: { gap: 8 },
  manualLabel: {
    fontSize: 12,
    fontFamily: Fonts.sansMedium,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    textAlign: 'left',
  },
  manualRow: { flexDirection: 'row', gap: 8 },
  manualInput: {
    flex: 1,
    height: 40,
    borderRadius: 6,
    borderWidth: 0.633,
    paddingLeft: 12, paddingRight: 12,
    fontSize: 14,
    fontFamily: Fonts.sans,
  },
  manualBtn: {
    paddingLeft: 16, paddingRight: 16,
    height: 40,
    borderRadius: 6,
    alignItems: 'center',
    justifyContent: 'center',
  },
  manualBtnText: { fontSize: 13, fontFamily: Fonts.sansSemiBold, textAlign: 'left' },
  errorText: { fontSize: 13, fontFamily: Fonts.sans, textAlign: 'left' },
  statusCenter: { alignItems: 'center', paddingTop: 24, paddingBottom: 24, gap: 12 },
  statusTitle: { fontSize: 17, fontFamily: Fonts.sansSemiBold, marginTop: 4, textAlign: 'center' },
  statusDesc: { fontSize: 14, fontFamily: Fonts.sans, textAlign: 'center', lineHeight: 20 },
  successCircle: {
    width: 56,
    height: 56,
    borderRadius: 28,
    alignItems: 'center',
    justifyContent: 'center',
  },
  errorCircle: {
    width: 56,
    height: 56,
    borderRadius: 28,
    alignItems: 'center',
    justifyContent: 'center',
  },
  errorActions: { gap: 8 },
  retryBtn: { height: 44, borderRadius: 8, alignItems: 'center', justifyContent: 'center' },
  retryBtnText: { fontSize: 15, fontFamily: Fonts.sansSemiBold, textAlign: 'left' },
  cancelBtn: {
    height: 44,
    borderRadius: 8,
    borderWidth: 0.633,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cancelBtnText: { fontSize: 15, fontFamily: Fonts.sansSemiBold, textAlign: 'left' },
  ipList: { gap: 4 },
  ipRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingLeft: 14, paddingRight: 14,
    paddingTop: 12, paddingBottom: 12,
    borderRadius: 8,
    borderWidth: 0.633,
  },
  ipInfo: { flex: 1 },
  ipText: { fontSize: 14, fontFamily: Fonts.sansMedium, textAlign: 'left' },
  ipPort: { fontSize: 12, fontFamily: Fonts.sans, marginTop: 1, textAlign: 'left' },
} as const;
