import { HAIRLINE_WIDTH } from "@/constants/layout";
import { Platform } from 'react-native';
import { Fonts } from '@/constants/theme';

export const styles = {
  wrapper: {
    paddingLeft: 12, paddingRight: 12,
    maxWidth: 1080,
    alignSelf: "center",
    width: "100%",
    overflow: "visible",
    zIndex: Platform.OS === "android" ? 9 : 11,
  },
  bar: {
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 2,
    paddingLeft: 2, paddingRight: 2,
    paddingBottom: 6,
  },
  anchor: {
    position: "relative",
  },
  control: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    height: 26,
    maxWidth: 240,
    paddingLeft: 7, paddingRight: 7,
    borderRadius: 6,
  },
  controlText: {
    fontSize: 12,
    fontFamily: Fonts.sansMedium,
    flexShrink: 1,
  },
  popover: {
    position: "absolute",
    bottom: "100%",
    left: 0,
    marginBottom: 6,
    minWidth: 240,
    maxWidth: 340,
    borderRadius: 10,
    borderWidth: 0.633,
    overflow: "hidden",
    boxShadow: "0px 4px 12px rgba(0, 0, 0, 0.15)",
    elevation: 8,
    zIndex: 20,
  },
  popoverScroll: {
    maxHeight: 260,
  },
  item: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
    paddingLeft: 10, paddingRight: 10,
    paddingTop: 7, paddingBottom: 7,
  },
  itemMain: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    flexShrink: 1,
  },
  itemLabels: {
    flexShrink: 1,
  },
  colorDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  itemText: {
    fontSize: 12.5,
    fontFamily: Fonts.sansMedium,
  },
  itemSub: {
    fontSize: 10.5,
    lineHeight: 14,
    fontFamily: Fonts.mono,
  },
  addProject: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    borderTopWidth: HAIRLINE_WIDTH,
    paddingLeft: 10, paddingRight: 10,
    paddingTop: 9, paddingBottom: 9,
  },
  addProjectText: {
    fontSize: 12,
    fontFamily: Fonts.sansMedium,
  },
  createBranchAction: { flexDirection: "row", alignItems: "center", gap: 8, borderTopWidth: HAIRLINE_WIDTH, paddingLeft: 10, paddingRight: 10, paddingTop: 9 , paddingBottom: 9 },
  createBranchText: { fontSize: 12, fontFamily: Fonts.sansMedium },
  branchOverlay: { flex: 1, alignItems: "center", justifyContent: "center", padding: 24, backgroundColor: "rgba(0,0,0,0.48)" },
  branchDialog: { width: "100%", maxWidth: 360, borderWidth: HAIRLINE_WIDTH, borderRadius: 12, padding: 20 },
  branchTitle: { fontSize: 16, fontFamily: Fonts.sansSemiBold },
  branchHint: { marginTop: 6, fontSize: 12, fontFamily: Fonts.sans },
  branchInput: { height: 38, marginTop: 16, borderWidth: HAIRLINE_WIDTH, borderRadius: 7, paddingLeft: 10, paddingRight: 10, fontSize: 13, fontFamily: Fonts.mono, outlineStyle: "none" } as any,
  branchError: { marginTop: 8, fontSize: 12, fontFamily: Fonts.sans },
  branchActions: { flexDirection: "row", justifyContent: "flex-end", gap: 8, marginTop: 18 },
  branchCancel: { height: 32, borderWidth: HAIRLINE_WIDTH, borderRadius: 7, paddingLeft: 13, paddingRight: 13, justifyContent: "center" },
  branchCreate: { height: 32, borderRadius: 7, paddingLeft: 13, paddingRight: 13, justifyContent: "center" },
  branchCreateText: { fontSize: 12, fontFamily: Fonts.sansMedium },
  loadingRow: {
    paddingTop: 16, paddingBottom: 16,
    alignItems: "center",
  },
  emptyText: {
    fontSize: 12,
    fontFamily: Fonts.sans,
    paddingLeft: 12, paddingRight: 12,
    paddingTop: 14, paddingBottom: 14,
  },
} as const;
