import { HAIRLINE_WIDTH } from "@/constants/layout";
import { Fonts } from "@/constants/theme";
import { SESSION_INDENT } from "./constants";

export const styles = {
  container: {
    flex: 1,
    height: "100%",
  },
  deleteOverlay: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    padding: 24,
    backgroundColor: "rgba(0,0,0,0.48)",
  },
  deleteDialog: {
    width: "100%",
    maxWidth: 360,
    borderWidth: HAIRLINE_WIDTH,
    borderRadius: 12,
    padding: 20,
    boxShadow: "0px 12px 32px rgba(0, 0, 0, 0.24)",
    elevation: 12,
  } as any,
  deleteTitle: {
    fontSize: 16,
    fontFamily: Fonts.sansSemiBold,
  },
  deleteDescription: {
    marginTop: 8,
    fontSize: 13,
    fontFamily: Fonts.sans,
  },
  deleteHint: {
    marginTop: 4,
    fontSize: 12,
    fontFamily: Fonts.sans,
  },
  deleteActions: {
    flexDirection: "row",
    justifyContent: "flex-end",
    gap: 8,
    marginTop: 20,
  },
  deleteCancel: {
    height: 32,
    borderWidth: HAIRLINE_WIDTH,
    borderRadius: 7,
    paddingLeft: 13, paddingRight: 13,
    justifyContent: "center",
  },
  deleteCancelText: {
    fontSize: 12,
    fontFamily: Fonts.sansMedium,
  },
  deleteConfirm: {
    height: 32,
    borderRadius: 7,
    paddingLeft: 13, paddingRight: 13,
    justifyContent: "center",
  },
  deleteConfirmText: {
    color: "#FFFFFF",
    fontSize: 12,
    fontFamily: Fonts.sansMedium,
  },
  serverRow: {
    borderBottomWidth: 0.633,
    zIndex: 20,
  },
  top: {
    paddingLeft: 8, paddingRight: 8,
    paddingTop: 8,
  },
  settingsHeader: {
    paddingLeft: 15, paddingRight: 15,
    paddingTop: 14,
    paddingBottom: 10,
  },
  settingsTitle: {
    fontSize: 16,
    lineHeight: 22,
    fontFamily: Fonts.sansSemiBold,
  },
  settingsContent: {
    gap: 3,
    paddingLeft: 8, paddingRight: 8,
    paddingBottom: 12,
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    paddingLeft: 8, paddingRight: 8,
    paddingBottom: 12,
  },
  sectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 1,
    paddingLeft: 8,
    paddingRight: 1,
    paddingTop: 16,
    paddingBottom: 2,
  },
  sectionTitle: {
    flex: 1,
    fontSize: 11,
    lineHeight: 16,
    letterSpacing: 0.4,
    fontFamily: Fonts.sansMedium,
  },
  headerAction: {
    width: 20,
    height: 20,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 4,
  },
  row: {
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
    height: 29,
    paddingLeft: 7, paddingRight: 7,
    borderRadius: 6,
  },
  rowMain: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
    height: "100%",
    minWidth: 0,
  },
  rowActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 1,
  },
  rowIcon: {
    width: 16,
    height: 20,
    alignItems: "center",
    justifyContent: "center",
  },
  rowLabel: {
    flex: 1,
    fontSize: 13.5,
    lineHeight: 19,
    fontFamily: Fonts.sans,
  },
  pinMark: {
    width: 3,
    height: 3,
    borderRadius: 1.5,
    opacity: 0.7,
  },
  rowAction: {
    width: 20,
    height: 20,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 4,
  },
  dot: {
    width: 5,
    height: 5,
    borderRadius: 2.5,
  },
  sessionRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    height: 26,
    paddingLeft: 8,
    paddingRight: 7,
    borderRadius: 6,
  },
  sessionMain: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    height: "100%",
    minWidth: 0,
  },
  sessionLead: {
    width: 16,
    alignItems: "center",
    justifyContent: "center",
  },
  sessionLabel: {
    flex: 1,
    fontSize: 12.5,
    lineHeight: 18,
  },
  sessionInput: {
    flex: 1,
    minWidth: 0,
    height: 22,
    paddingLeft: 0, paddingRight: 0,
    paddingTop: 0, paddingBottom: 0,
    fontSize: 12.5,
    lineHeight: 18,
  },
  sessionActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 1,
  },
  sessionLoading: {
    alignSelf: "flex-start",
    marginLeft: SESSION_INDENT,
    marginTop: 5, marginBottom: 5,
  },
  sessionEmpty: {
    fontSize: 12,
    lineHeight: 18,
    fontFamily: Fonts.sans,
    paddingLeft: SESSION_INDENT,
    paddingTop: 5, paddingBottom: 5,
  },
  moreRow: {
    height: 24,
    justifyContent: "center",
    paddingLeft: SESSION_INDENT,
  },
  moreText: {
    fontSize: 12,
    lineHeight: 18,
    fontFamily: Fonts.sans,
  },
  empty: {
    fontSize: 12.5,
    lineHeight: 18,
    fontFamily: Fonts.sans,
    paddingLeft: 8, paddingRight: 8,
    paddingTop: 5, paddingBottom: 5,
  },
  footer: {
    borderTopWidth: HAIRLINE_WIDTH,
    paddingLeft: 8, paddingRight: 8,
    paddingTop: 6, paddingBottom: 6,
  },
} as const;
